import { MigrationInterface, QueryRunner } from "typeorm";

export class Migration1730787365479 implements MigrationInterface {
    name = 'Migration1730787365479'

    public async up(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "guestbook" ADD "description" text DEFAULT ''`);
        await queryRunner.query(`ALTER TABLE "guestbook" DROP CONSTRAINT "guestbook_pkey"`);
        await queryRunner.query(`ALTER TABLE "guestbook" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "guestbook" ADD "id" SERIAL NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guestbook" ADD CONSTRAINT "PK_6e363d41bc2ab0800429aa42e60" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "guestbook" ALTER COLUMN "title" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guestbook" ALTER COLUMN "title" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "guestbook" ALTER COLUMN "content" SET NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guestbook" ALTER COLUMN "content" DROP DEFAULT`);
        await queryRunner.query(`ALTER TABLE "guestbook" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "guestbook" ADD "createdAt" TIMESTAMP NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "guestbook" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "guestbook" ADD "updatedAt" TIMESTAMP NOT NULL DEFAULT now()`);
    }

    public async down(queryRunner: QueryRunner): Promise<void> {
        await queryRunner.query(`ALTER TABLE "guestbook" DROP COLUMN "updatedAt"`);
        await queryRunner.query(`ALTER TABLE "guestbook" ADD "updatedAt" TIMESTAMP WITH TIME ZONE DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "guestbook" DROP COLUMN "createdAt"`);
        await queryRunner.query(`ALTER TABLE "guestbook" ADD "createdAt" TIMESTAMP WITH TIME ZONE NOT NULL DEFAULT now()`);
        await queryRunner.query(`ALTER TABLE "guestbook" ALTER COLUMN "content" SET DEFAULT ' '`);
        await queryRunner.query(`ALTER TABLE "guestbook" ALTER COLUMN "content" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guestbook" ALTER COLUMN "title" SET DEFAULT ' '`);
        await queryRunner.query(`ALTER TABLE "guestbook" ALTER COLUMN "title" DROP NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guestbook" DROP CONSTRAINT "PK_6e363d41bc2ab0800429aa42e60"`);
        await queryRunner.query(`ALTER TABLE "guestbook" DROP COLUMN "id"`);
        await queryRunner.query(`ALTER TABLE "guestbook" ADD "id" bigint GENERATED BY DEFAULT AS IDENTITY NOT NULL`);
        await queryRunner.query(`ALTER TABLE "guestbook" ADD CONSTRAINT "guestbook_pkey" PRIMARY KEY ("id")`);
        await queryRunner.query(`ALTER TABLE "guestbook" DROP COLUMN "description"`);
    }

}
